### ISSUE TITLE
jooq: what's the use of LoggingExecutionListener?

### ISSUE THREAD

**Issue by victornoel** [benjamin-bader/droptools#38]
Hi

In Jooq there is already `LoggerListener`, why do we need `LoggingExecutionListener` then?
Is that some remnant of an old time when there wasn't any SQL logger?

The jooq `LoggerListener` seems to handle lots of corner cases in any case.

**Comment by benjamin-bader** [comment]
I don't actually remember why!  As far as I recall, it didn't play nicely with SLF4J, but looking at the code today it claims that it does.  Maybe I just didn't know about it.  Have you tried it out

**Comment by victornoel** [comment]
ok, I will do some tests and compare them and get back to you on that :)

**Comment by victornoel** [comment]
@benjamin-bader for the record, I have used `LoggerListener` from jooq multiple time in a slf4j environment without any problems.

I suppose `LoggingExecutionListener` can be removed :)

(sorry for the delay!)

**Comment by benjamin-bader** [comment]
Oh, well, great!  I'm always happy to delete code :D

Thanks!

**Comment by benjamin-bader** [comment]
You know, looking through the code for jooq's `LoggerListener`, I remember why I wrote `LoggingExecutionListener` - it's because the former is quite verbose, and at the time I just wanted to see the formatted SQL query!

When I think about it now, though, I don't really care that jooq's is more verbose; seems worthwhile for us to have less code and a smaller configuration API.
