### ISSUE TITLE
Is there a way to get the DSL context outside of a Resource?

### ISSUE THREAD

**Issue by htamas** [benjamin-bader/droptools#46]
For example on application start. I want to use jOOQ in repository classes, not directly in my resources.

**Comment by benjamin-bader** [comment]
There are a few ways you could do it.  The most obvious way is to just use the `JooqFactory` from your application's configuration (e.g. https://github.com/benjamin-bader/droptools/blob/master/droptools-example/src/main/java/com/bendb/example/ExampleConfig.java#L32) and wire it up to your repositories manually.

You might also look in to using HK2, which is how we do the Resource-level injection.  I think that we bind DSL contexts in request-scope by default, so that probably wouldn't be appropriate, but take a look at `JooqBinder` - maybe it will point you in a useful direction.

**Comment by htamas** [comment]
Thanks a lot!
